version: "3"

services:
# web -----------------------------------------------------------------------
  web:
    image: nginx
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ../application/webroot:/var/www/html
    ports:
    - 9100:80

# php -----------------------------------------------------------------------
  php:
#   image:  php:7.4-fpm
    build: ./php
    volumes:
    - ../application:/var/www/html
    
# mysql ---------------------------------------------------------------------
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER:          example
      MYSQL_PASSWORD:      example
      MYSQL_DATABASE:      example
    ports:
      - 3306:3306

# adminer -------------------------------------------------------------------
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080